name = "cms-worker"
main = "src/worker.ts"
compatibility_date = "2024-10-11"
account_id = "ID"

assets = { directory = "./public/" }

d1_databases = [
  { binding = "DB", database_name = "db", database_id = "DB_ID" }
]

[[r2_buckets]]
binding = 'FILES'
bucket_name = 'BUCKET'
preview_bucket_name = 'files'
